### ISSUE TITLE
Feature request: allow non-persistent attributes or/and stores

### ISSUE THREAD

**Issue by Uninen** [charlesgael/tauri-pinia#1]
First, thanks for this library, it's a very nice and easy to use alternative to more traditional options! 👍 

### I'm submitting a ...

- [ ] bug report
- [x] feature request
- [ ] question about the decisions made in the repository
- [ ] question about how to use this project

### Summary

I'd like to have a way to mark either a store or an attribute of a state non-persistent so that it would always be based on the provided initial value. Currently for example something like `appInitReady: false` which gets toggled to true in `init()` action is currently stored as true on disk and the logic needs to be rewritten in order to work w/ tauri-pinia. There are many cases where empty / predefined initial values would be useful.

Initial ideas:

- allow marking non-persistent attributes in config (something in the lines of `await tauriPinia({ excludedAttrs: ['debug', 'isInited', 'createdAt'] })`)
- offer an api to mark store not to be persisted (in config or maybe easier via a state attribute like `dontPersist: true`)

**Comment by charlesgael** [comment]
New version released, see changelog.
Sorry for the wait, lots of things to do.
Should you have any more ideas, will be happy to implement them.

**Comment by Uninen** [comment]
This is open source, you shouldn't stress about self-imposed schedules. The feature looks great, Big Thanks for the addition! 🙏
